# Generated by Django 5.2.1 on 2025-06-22 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SparepartView',
            fields=[
                ('partid', models.BigIntegerField(db_column='partID', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_id', models.BigIntegerField(blank=True, null=True)),
                ('inactive', models.BooleanField(blank=True, null=True)),
                ('supplier_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sparepart_view',
                'ordering': ['partid'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPartModel',
            fields=[
                ('part_model_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_part_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblpartslist',
            fields=[
                ('partid', models.BigAutoField(db_column='partID', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('part_number', models.CharField(db_column='part number', max_length=100)),
                ('short_name', models.CharField(db_column='Short Name', max_length=100)),
                ('inactive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tblPartsList',
                'ordering': ['partid'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblpartsprice',
            fields=[
                ('priceid', models.BigAutoField(db_column='priceID', primary_key=True, serialize=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('effectivedate', models.DateField(db_column='EffectiveDate', default=datetime.date.today)),
            ],
            options={
                'db_table': 'tblPartsPrice',
                'managed': False,
            },
        ),
    ]
