# Generated by Django 5.2.1 on 2025-06-22 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetView',
            fields=[
                ('assetid', models.BigIntegerField(blank=True, db_column='AssetID', primary_key=True, serialize=False, verbose_name='Asset ID')),
                ('customerassetnumber', models.CharField(blank=True, db_column='CustomerAssetNumber', max_length=255, null=True, verbose_name='Cust Asset')),
                ('serialnumber', models.CharField(blank=True, db_column='SerialNumber', max_length=255, null=True, verbose_name='SN')),
                ('lastppmdate', models.DateField(blank=True, null=True, verbose_name='Last PPM Date')),
                ('lastrepairdate', models.DateField(blank=True, null=True, verbose_name='Last Repair Date')),
                ('lastjobdate', models.DateField(blank=True, null=True)),
                ('creationdate', models.DateField(blank=True, null=True)),
                ('contractid', models.BigIntegerField(blank=True, null=True)),
                ('installationdate', models.DateField(blank=True, null=True)),
                ('unitprice', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ordernumber', models.CharField(blank=True, null=True)),
                ('ordervalue', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('nextppmdate', models.DateField(blank=True, null=True)),
                ('softwareversion', models.CharField(blank=True, null=True, verbose_name='Software')),
                ('support_level_id', models.BigIntegerField(blank=True, null=True)),
                ('customername', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer')),
                ('modelname', models.CharField(blank=True, db_column='ModelName', max_length=100, null=True, verbose_name='Model')),
                ('brandname', models.CharField(blank=True, db_column='BrandName', null=True, verbose_name='Brand')),
                ('locationname', models.CharField(blank=True, null=True, verbose_name='Location')),
                ('sitename', models.CharField(blank=True, null=True, verbose_name='Site')),
                ('categoryname', models.CharField(blank=True, null=True, verbose_name='Category')),
                ('schedulename', models.CharField(blank=True, null=True)),
                ('status_name', models.CharField(blank=True, null=True, verbose_name='Status')),
                ('support_level_name', models.CharField(blank=True, null=True)),
                ('ppm_compliance', models.TextField(blank=True, null=True, verbose_name='PPM_Compliance')),
            ],
            options={
                'db_table': 'asset_view',
                'ordering': ('assetid',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('jobid', models.BigIntegerField(db_column='JobID', primary_key=True, serialize=False)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('workdone', models.TextField(blank=True, db_column='WorkDone', null=True)),
                ('technician_name', models.CharField(blank=True, db_column='Technician Name', max_length=100, null=True)),
                ('partsperjob', models.TextField(blank=True, db_column='PartsPerJob', null=True)),
                ('testsperjob', models.TextField(blank=True, db_column='TestsPerJob', null=True)),
                ('serialnumber', models.CharField(blank=True, db_column='SerialNumber', max_length=255, null=True)),
                ('model', models.CharField(blank=True, db_column='Model', max_length=100, null=True)),
                ('customer', models.CharField(blank=True, db_column='Customer', max_length=100, null=True)),
                ('jobstatus', models.CharField(blank=True, db_column='JobStatus', max_length=100, null=True)),
                ('jobtypename', models.CharField(blank=True, max_length=50, null=True)),
                ('total_cost', models.DecimalField(blank=True, db_column='Total Cost', decimal_places=2, max_digits=100, null=True)),
                ('customerasset', models.CharField(blank=True, db_column='CustomerAsset', max_length=255, null=True)),
                ('customer_address', models.CharField(blank=True, db_column='Customer Address', max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, db_column='Customer Phone', max_length=100, null=True)),
                ('brandname', models.CharField(blank=True, db_column='BrandName', null=True)),
                ('customer_postcode', models.CharField(blank=True, db_column='Customer Postcode', null=True)),
            ],
            options={
                'db_table': 'jobSummary',
                'ordering': ('jobid',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblassets',
            fields=[
                ('assetid', models.BigAutoField(db_column='AssetID', primary_key=True, serialize=False)),
                ('customerassetnumber', models.CharField(blank=True, db_column='CustomerAssetNumber', max_length=255, null=True)),
                ('serialnumber', models.CharField(db_column='SerialNumber', max_length=255)),
                ('lastppmdate', models.DateField(blank=True, null=True)),
                ('lastrepairdate', models.DateField(blank=True, null=True)),
                ('lastjobdate', models.DateField(blank=True, null=True)),
                ('creationdate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('installationdate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('unitprice', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ordernumber', models.CharField(blank=True, null=True)),
                ('ordervalue', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('nextppmdate', models.DateField(blank=True, null=True)),
                ('softwareversion', models.CharField(blank=True, null=True)),
                ('prod_date', models.DateField(blank=True, null=True)),
                ('is_test_eq', models.BooleanField(blank=True, default=False, null=True)),
                ('next_calibration_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblAssets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblassetscontracts',
            fields=[
                ('assetcontractid', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationdate', models.DateField()),
            ],
            options={
                'db_table': 'tblassetscontracts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAssetStatus',
            fields=[
                ('asset_status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField()),
            ],
            options={
                'db_table': 'tbl_asset_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblbrands',
            fields=[
                ('brandid', models.BigAutoField(db_column='BrandID', primary_key=True, serialize=False)),
                ('brandname', models.CharField(db_column='BrandName', unique=True)),
            ],
            options={
                'db_table': 'tblBrands',
                'ordering': ['brandid'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcategories',
            fields=[
                ('categoryid', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField()),
                ('categorydescription', models.TextField(blank=True, null=True)),
                ('gmdnname', models.CharField(blank=True, null=True)),
                ('gmdncode', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblcategories',
                'ordering': ['categoryid'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcheckslists',
            fields=[
                ('testname', models.CharField(db_column='Test', max_length=100)),
                ('testid', models.BigAutoField(db_column='testID', primary_key=True, serialize=False)),
                ('test_description', models.TextField(db_column='Test Description')),
            ],
            options={
                'db_table': 'tblChecksLists',
                'ordering': ['testid'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcontractstatus',
            fields=[
                ('contractstatusid', models.BigAutoField(primary_key=True, serialize=False)),
                ('statusname', models.CharField()),
            ],
            options={
                'db_table': 'tblcontractstatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcontracttype',
            fields=[
                ('contracttypeid', models.BigAutoField(primary_key=True, serialize=False)),
                ('contracttypename', models.CharField()),
            ],
            options={
                'db_table': 'tblcontracttype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcustomer',
            fields=[
                ('customer_name', models.CharField(db_column='Customer Name', max_length=100, unique=True)),
                ('customer_address', models.CharField(blank=True, db_column='Customer Address', max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, db_column='Customer Phone', max_length=100, null=True)),
                ('customerid', models.BigAutoField(db_column='CustomerID', primary_key=True, serialize=False)),
                ('customer_postcode', models.CharField(blank=True, db_column='Customer Postcode', null=True)),
            ],
            options={
                'db_table': 'tblCustomer',
                'ordering': ['customerid'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tblest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbljob',
            fields=[
                ('jobid', models.BigAutoField(db_column='JobID', primary_key=True, serialize=False)),
                ('jobstartdate', models.DateField(blank=True, db_column='JobStartDate', null=True)),
                ('jobenddate', models.DateField(blank=True, db_column='JobEndDate', null=True)),
                ('comments', models.CharField(blank=True, db_column='Comments', null=True)),
                ('workdone', models.TextField(blank=True, db_column='WorkDone', null=True)),
                ('creationdate', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'tblJob',
                'ordering': ('jobid',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbljobstatus',
            fields=[
                ('jobstatus', models.CharField(blank=True, db_column='JobStatus', max_length=100, null=True)),
                ('jobstatusid', models.BigIntegerField(db_column='JobStatusID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tblJobStatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbljobtypes',
            fields=[
                ('jobtypeid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('jobtypename', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tblJobTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbllocations',
            fields=[
                ('locationid', models.BigAutoField(primary_key=True, serialize=False)),
                ('locationname', models.CharField()),
                ('departmentname', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbllocations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblmaintContracts',
            fields=[
                ('contractid', models.BigAutoField(primary_key=True, serialize=False)),
                ('contractname', models.CharField()),
                ('purchaseorder', models.CharField(blank=True, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'tblmaint_contracts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMaintenanceSupplier',
            fields=[
                ('supplier_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maint_supplier_name', models.CharField(unique=True)),
                ('maint_supplier_contact', models.CharField(blank=True, null=True)),
                ('maint_supplier_email', models.CharField(blank=True, null=True)),
                ('maint_supplier_phone', models.CharField(blank=True, null=True)),
                ('main_supplier_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_maintenance_supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblmodel',
            fields=[
                ('modelname', models.CharField(db_column='ModelName', max_length=100)),
                ('modelid', models.BigAutoField(db_column='ModelID', primary_key=True, serialize=False)),
                ('gtin', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblModel',
                'ordering': ['modelid'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblpartsused',
            fields=[
                ('quantity', models.IntegerField(db_column='Quantity', default=1)),
                ('partsusedid', models.BigAutoField(db_column='PartsUsedID', primary_key=True, serialize=False)),
                ('unitprice', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
            ],
            options={
                'db_table': 'tblPartsUsed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblppmschedules',
            fields=[
                ('scheduleid', models.BigAutoField(primary_key=True, serialize=False)),
                ('schedulename', models.CharField(blank=True)),
                ('schedulemetric', models.CharField(blank=True, null=True)),
                ('schedulefrequency', models.IntegerField()),
            ],
            options={
                'db_table': 'tblppmschedules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblsites',
            fields=[
                ('siteid', models.BigAutoField(primary_key=True, serialize=False)),
                ('sitename', models.CharField(unique=True)),
            ],
            options={
                'db_table': 'tblsites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSupportLevel',
            fields=[
                ('support_level_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('support_level_name', models.CharField(unique=True)),
                ('support_level_description', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_support_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbltechnicianlist',
            fields=[
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('technicianid', models.BigIntegerField(db_column='TechnicianID', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'tblTechnicianList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbltesteq',
            fields=[
                ('testeqid', models.BigAutoField(db_column='TestEqID', primary_key=True, serialize=False)),
                ('last_calibration_date', models.DateField(blank=True, db_column='Last Calibration Date', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=100, null=True)),
                ('serialnumber', models.CharField(db_column='SerialNumber', max_length=100)),
                ('comment', models.CharField(blank=True, db_column='Comment', max_length=100, null=True)),
            ],
            options={
                'db_table': 'tblTestEq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbltesteqused',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tblTestEqUsed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbltestresult',
            fields=[
                ('resultid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('resultname', models.CharField()),
            ],
            options={
                'db_table': 'tbltestresult',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbltestscarriedout',
            fields=[
                ('testid', models.BigAutoField(db_column='TestID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tblTestsCarriedOut',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbltotaljobcost',
            fields=[
                ('totalcostid', models.BigAutoField(primary_key=True, serialize=False)),
                ('totalcost', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
            ],
            options={
                'db_table': 'tbltotaljobcost',
                'managed': False,
            },
        ),
    ]
