# Generated by Django 5.2.1 on 2025-08-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblassets',
            options={'managed': False, 'permissions': [('bulk_update_assets', 'Can perform bulk updates')]},
        ),
        migrations.AlterModelOptions(
            name='tbljob',
            options={'managed': False, 'ordering': ('jobid',), 'permissions': [('bulk_update', 'Can perform bulk updates')]},
        ),
    ]
