# Generated by Django 5.2.1 on 2025-08-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_tblassets_options_alter_tbljob_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbljob',
            options={'managed': False, 'ordering': ('jobid',), 'permissions': [('bulk_update_tbljob', 'Can perform bulk updates'), ('genreport_tbljob', 'Can download job reports')]},
        ),
    ]
