# Generated by Django 5.2.1 on 2025-08-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_tbljob_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblassets',
            options={'managed': False, 'permissions': [('bulk_change_assets', 'Can perform bulk updates')]},
        ),
    ]
