# Generated by Django 5.2.1 on 2025-08-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_tblassets_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblmodel',
            options={'managed': False, 'ordering': ['modelid'], 'permissions': [('bulk_update_tblmodel', 'Can perform bulk updates')]},
        ),
    ]
