# Generated by Django 6.0 on 2026-07-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentConfiguration',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'equipment_configuration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentConfigurationLink',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('removed_on', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'equipment_configuration_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentConfigurationModel',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('mandatory', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'equipment_configuration_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentConfigurationScope',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'equipment_configuration_scope',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentConfigurationStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_terminal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'equipment_configuration_status',
                'ordering': ['sort_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentSoftware',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('removed_on', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'equipment_software',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=100)),
                ('version_number', models.IntegerField(default=1)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('gtin', models.CharField(blank=True, max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'software',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoftwareModel',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('mandatory', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'software_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoftwareType',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'software_type',
                'ordering': ['name'],
                'managed': False,
            },
        ),
    ]
