# Generated by Django 5.2.1 on 2025-09-29 07:30

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsView',
            fields=[
                ('document_id', models.BigIntegerField(blank=True, null=True, verbose_name='Document ID')),
                ('document_name', models.CharField(blank=True, null=True, verbose_name='Document Name')),
                ('document_description', models.TextField(blank=True, null=True)),
                ('document_link_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Link ID')),
                ('link_row', models.BigIntegerField(blank=True, null=True)),
                ('table_name', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documents_view2',
                'ordering': ['document_link_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDocTableRef',
            fields=[
                ('table_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(unique=True)),
            ],
            options={
                'db_table': 'tbl_doc_table_ref',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDocumentLinks',
            fields=[
                ('document_link_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link_row', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tbl_document_links',
                'ordering': ['document_link_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDocuments',
            fields=[
                ('document_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField()),
                ('document_description', models.TextField(blank=True, null=True)),
                ('document_bytea', models.BinaryField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('document_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'db_table': 'tbl_aws_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDocumentTypes',
            fields=[
                ('document_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_type_name', models.CharField()),
            ],
            options={
                'db_table': 'tbl_document_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemporaryUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/app/media/temp_uploads'), upload_to='')),
                ('mime_type', models.CharField(max_length=100)),
                ('original_name', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tbl_temporaryupload',
                'managed': False,
            },
        ),
    ]
