# Generated by Django 5.2.1 on 2026-04-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblDocumentTypes',
        ),
        migrations.AlterModelOptions(
            name='tbldocumentlinks',
            options={'managed': False, 'ordering': ['document_link_id'], 'permissions': [('bulk_create_links', 'Can bulk create links')]},
        ),
    ]
