# Generated by Django 5.2.1 on 2026-04-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_delete_tbldocumenttypes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbldocumentlinks',
            options={'managed': False, 'ordering': ['document_link_id'], 'permissions': [('bulk_create_links', 'Can bulk create links'), ('bulk_delete_links', 'Can bulk delete links')]},
        ),
    ]
