# Generated by Django 5.2.1 on 2026-04-05 11:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_tbldocumentlinks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUploadGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type_id', models.IntegerField(choices=[(0, 'UNKNOWN'), (10, 'User Manual'), (20, 'Service Manual'), (30, 'Invoice'), (40, 'Delivery Note'), (50, 'Service Report')], default=0)),
                ('combined_ocr_text', models.TextField(blank=True)),
                ('extracted_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
