# Generated by Django 6.0 on 2026-05-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_tempuploadgroup'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tempuploadgroup',
            table='temp_upload_group',
        ),
    ]
