# Generated by Django 5.2.1 on 2025-06-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverylineview',
            fields=[
                ('delivery_id', models.BigIntegerField(blank=True, null=True)),
                ('po_id', models.BigIntegerField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_note_number', models.CharField(blank=True, null=True)),
                ('qty', models.BigIntegerField(blank=True, null=True)),
                ('part_number', models.CharField(blank=True, db_column='part number', max_length=100, null=True)),
                ('short_name', models.CharField(blank=True, db_column='Short Name', max_length=100, null=True)),
                ('line_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'deliverylineview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Outstandngdeliveriesview',
            fields=[
                ('outstanding_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('po_id', models.BigIntegerField(blank=True, null=True)),
                ('qty_ordered', models.IntegerField(blank=True, null=True)),
                ('qty_delivered', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('line_description', models.TextField(blank=True, null=True)),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('outstanding', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outstandngDeliveriesView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PoView',
            fields=[
                ('po_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date_raised', models.DateField(blank=True, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('po_total', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('order_status_id', models.BigIntegerField(blank=True, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('line_id', models.BigIntegerField(blank=True, null=True)),
                ('item_id', models.BigIntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('qty_ordered', models.BigIntegerField(default=1)),
                ('line_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('line_status_id', models.BigIntegerField(blank=True, null=True)),
                ('line_description', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('first_line', models.TextField(blank=True, null=True)),
                ('postcode', models.CharField(blank=True, null=True)),
                ('supplier_name', models.TextField(blank=True, null=True)),
                ('addr_first_line', models.TextField(blank=True, null=True)),
                ('addr_postcode', models.TextField(blank=True, null=True)),
                ('partnumber', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'po_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDeliveries',
            fields=[
                ('delivery_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('delivery_note_number', models.CharField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'tbl_deliveries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDeliveryAddresses',
            fields=[
                ('addr_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_line', models.TextField(blank=True, null=True)),
                ('postcode', models.CharField(blank=True, null=True)),
                ('address_alias', models.CharField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_delivery_addresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDeliveryLines',
            fields=[
                ('line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.BigIntegerField(blank=True, null=True)),
                ('line_description', models.CharField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'tbl_delivery_lines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblExpenses',
            fields=[
                ('expense_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('payment_to', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_expenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblExpenseStatus',
            fields=[
                ('status_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_expense_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblInvoices',
            fields=[
                ('invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_no', models.CharField()),
                ('invoice_date', models.DateField()),
                ('invoice_due_date', models.DateField(blank=True, null=True)),
                ('fully_paid_date', models.DateField(blank=True, null=True)),
                ('invoice_amount', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
            options={
                'db_table': 'tbl_invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblInvoiceStatus',
            fields=[
                ('invoice_status_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('invoice_status_name', models.CharField()),
                ('invoice_status_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_invoice_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblOrderStatus',
            fields=[
                ('order_status_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('order_status_name', models.TextField()),
            ],
            options={
                'db_table': 'tbl_order_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPoLines',
            fields=[
                ('line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('qty_ordered', models.BigIntegerField(default=1)),
                ('line_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('qty_delivered', models.BigIntegerField(blank=True, null=True)),
                ('line_status_id', models.BigIntegerField(blank=True, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('line_price_incl_vat', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('line_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_po_lines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPurchaseOrder',
            fields=[
                ('po_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_raised', models.DateField()),
                ('sub_total', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('po_total', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'tbl_purchase_order',
                'ordering': ['-po_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSuppliers',
            fields=[
                ('supplier_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.TextField(unique=True)),
                ('addr_first_line', models.TextField()),
                ('addr_second_line', models.TextField(blank=True, null=True)),
                ('addr_postcode', models.TextField()),
                ('email_address', models.TextField()),
                ('vat_registration_number', models.CharField(blank=True, null=True)),
                ('company_registration_number', models.CharField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_suppliers',
                'managed': False,
            },
        ),
    ]
