# Generated by Django 5.2.1 on 2025-08-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblinvoices',
            options={'managed': False, 'permissions': [('bulk_update_tblinvoices', 'Can perform bulk updates')]},
        ),
    ]
