# Generated by Django 5.2.1 on 2025-11-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_alter_tblinvoices_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblOrderUnit',
            fields=[
                ('order_unit_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('order_unit_name', models.CharField()),
            ],
            options={
                'db_table': 'tbl_order_unit',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='tblinvoices',
            options={'managed': False, 'ordering': ('-invoice_date',), 'permissions': [('bulk_update_tblinvoices', 'Can perform bulk updates')]},
        ),
    ]
