# Generated by Django 6.0 on 2026-07-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalAcquisition',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('statusdate', models.DateTimeField(blank=True, editable=False, null=True)),
                ('targetdate', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('approvedquantity', models.IntegerField(blank=True, null=True)),
                ('orderno', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'capital_acquisition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CapitalAcquisitionStatus',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('inactive', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'capital_acquisition_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CapitalProject',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('creationdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificationdate', models.DateTimeField(auto_now=True, null=True)),
                ('inactive', models.BooleanField(blank=True, null=True)),
                ('startdate', models.DateTimeField(blank=True, null=True)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'capital_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CapitalProjectEquipment',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'capital_project_equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CapitalProjectStatus',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('inactive', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'capital_project_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CapitalProjectType',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('inactive', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'capital_project_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionRequest',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('creationdate', models.DateTimeField(blank=True, null=True)),
                ('configuration', models.TextField(blank=True, null=True)),
                ('isnew', models.BooleanField(blank=True, null=True)),
                ('orderno', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unitprice', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('unitpricevat', models.FloatField(blank=True, null=True)),
                ('warrantymonths', models.IntegerField(blank=True, null=True)),
                ('inactive', models.BooleanField(blank=True, null=True)),
                ('purchasedate', models.DateTimeField(blank=True, null=True)),
                ('installationdate', models.DateTimeField(blank=True, null=True)),
                ('orderdate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'commission_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionRequestStatus',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'commission_request_status',
                'managed': False,
            },
        ),
    ]
